version: '3.9'

services:
  failed-backend:
    container_name: shipments-service-failed-messages-monitoring-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency-base
    ports:
      - ${APP_FORWARD_PORT:-8081}:${APP_PORT:-8081}
    volumes:
      - .:/app
    networks:
      - shipments_service_network
    restart: unless-stopped
    tty: true
    stdin_open: true
    expose:
      - ${APP_PORT:-8081}
    
networks:
  shipments_service_network:
    name: shipments-service-shared-network
    external: true


# volumes:
#   postgresql-data:
#     driver: local
#   pgadmin-data:
#     driver: local
#   rabbitmq-data:
#     driver: local
#   rabbitmq-logs:
#     driver: local

